### ISSUE TITLE
Suggestion for language implementation additions

### ISSUE THREAD

**Issue by jpaquim** [appcypher/awesome-wasm-langs#108]
### TypeScript
- https://github.com/ASDAlexander77/TypeScriptCompiler
- https://github.com/TurboScriptLang/spec/blob/master/spec.md seems to be the more up-to-date resource on TurboScript, although it looks unmaintained for a few years

### Lisp/Scheme-like languages:
- https://github.com/yuriy-chumak/ol, demo at https://yuriy-chumak.github.io/ol/
- https://github.com/janet-lang/janet, demo at https://janet-lang.org/
- https://github.com/PollRobots/scheme, demo at https://pollrobots.com/scheme/
- https://github.com/LingDong-/wax, compiler demo at https://waxc.netlify.app/
- https://github.com/mbrock/wisp, demo at https://wisp.town/ (seems to be currently down, may be unmaintained)
- https://github.com/CalmSystem/wala

### Rebol
- https://github.com/hostilefork/replpad-js, demo at
http://hostilefork.com/media/shared/replpad-js/ (most of the code at https://github.com/metaeducation/ren-c)

### Toy implementations:
- https://github.com/drew-y/wispy
- https://github.com/wingo/wasm-jit, demo at https://wingolog.org/archives/2022/08/18/just-in-time-code-generation-within-webassembly
- https://github.com/binji/raw-wasm#jit, demo at https://binji.github.io/raw-wasm/jit
- https://github.com/mew-cx/chaitin_lisp, demo at http://weitz.de/chaitin/
- https://soi-disant.srht.site/entries/back-to-space.html

### emscripten-based
These language implementations support emscripten so in theory should be compilable to Wasm, although I've only seen JS builds so far:

- https://github.com/ashinn/chibi-scheme
- https://github.com/gambit/gambit
- https://github.com/vyzo/gerbil
- https://github.com/arturo-lang/arturo

**Comment by appcypher** [comment]
Coming late but can you make a PR out of this?
