### ISSUE TITLE
Scheme

### ISSUE THREAD

**Issue by pannous** [appcypher/awesome-wasm-langs#11]
https://github.com/google/schism

**Comment by appcypher** [comment]
I like that someone is working on Scheme-to-wasm compiler but I'm crazy busy now.
It will be awesome if you can make a PR.

**Comment by MITLISP** [comment]
I would like to tackle this!although I dont have too much experience, scheme is the first language I was taught. Any help would be appreciated and since Im not working I can devote myself to this

**Comment by appcypher** [comment]
Oh, okay then. Will add to the list asap.

**Comment by appcypher** [comment]
Done
