### ISSUE TITLE
What are the requirements for the list?

### ISSUE THREAD

**Issue by Horcrux7** [appcypher/awesome-wasm-langs#13]
What status must a project/tool have to add to this nice list? Does it have to be ready for production? Or you can also add projects with an early status like [JWebAssembly](https://github.com/i-net-software/JWebAssembly)?

**Comment by appcypher** [comment]
It doesn't have to be ready for production, as long as such project is actively maintained and working towards generating a wasm/wast IR. You can see that from the language list at the top of the readme. I used emojis to show the state they are in.

> ordinary eggshell means the project is in works but not ready for production use.
> a chick coming out of eggshell means the project is not yet stable but people can now use it.
> a chick without the eggshell means the project is stable for production usage.

**Comment by Horcrux7** [comment]
Ok, I understand.
* I have oversee this because it marks the languages and not the project. I think the languages should be already production ready.
* This will work if there is only one project/tool per language. If a language has more as one project then all projects must have the same state?
* A legend is ever a good idea. There is ever a douchebag like me that not understand it.
