### ISSUE TITLE
List source map support

### ISSUE THREAD

**Issue by eerorika** [appcypher/awesome-wasm-langs#2]
Suggestion / feature request: List which languages / compilers support [source maps](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k), and which do not.

**Comment by AppCypher** [comment]
Sounds like a nice idea. I will look into it.

**Comment by appcypher** [comment]
As a matter of fact, I can't look into it. This made sense 6 years ago when there was just a handful implementations. There are so many implementations (many undocumented) that I can't achieve this alone. I don't think it is realistic to expect this anymore.
