### ISSUE TITLE
Nim

### ISSUE THREAD

**Issue by pannous** [appcypher/awesome-wasm-langs#25]

**Comment by pannous** [comment]
https://github.com/stisa/nwasm
https://github.com/Feneric/nim-wasm-helpers
hatched_chick

**Comment by appcypher** [comment]
Nice!
It would be nice if you can create a PR for this. 
Thanks

**Comment by nicolo-ribaudo** [comment]
H

**Comment by pannous** [comment]
done https://github.com/appcypher/awesome-wasm-langs/pull/29
