### ISSUE TITLE
Turn into Awesome List

### ISSUE THREAD

**Issue by styfle** [appcypher/awesome-wasm-langs#3]
[![Awesome](https://awesome.re/badge.svg)](https://awesome.re) 

Everyone likes sunglasses and lists that are awesome!

Considering making this repo `awesome-wasm-langs` or something so that people know this is a list of web assembly languages.

https://github.com/sindresorhus/awesome/blob/master/awesome.md

**Comment by AppCypher** [comment]
Nice suggestion

**Comment by styfle** [comment]
Here's a related list: https://github.com/mbasso/awesome-wasm

**Comment by appcypher** [comment]
I believe the list is an awesome one now.
