### ISSUE TITLE
Add MicroPython

### ISSUE THREAD

**Issue by rafi16jan** [appcypher/awesome-wasm-langs#41]
MicroPython already have an official WebAssembly [port](https://github.com/micropython/micropython/tree/master/ports/javascript)

Also I made an NPM module to use it on Node or Webpack [here](https://www.npmjs.com/package/micropython)

**Comment by appcypher** [comment]
Cool. It would be nice if you raised a PR for this.

**Comment by appcypher** [comment]
Done
