### ISSUE TITLE
Scopes also compiles to wasm

### ISSUE THREAD

**Issue by porky11** [appcypher/awesome-wasm-langs#50]
[Scopes](http://scopes.rocks) also compiles to wasm. You can see an example how to do it [here](
https://bitbucket.org/duangle/scopes/src/default/testing/test_wasm.sc)

**Comment by appcypher** [comment]
Great. Please create a PR for it. Will gladly merge.

**Comment by OAyomide** [comment]
I am making a PR for this since @porky11 doesnt seem to take it up

**Comment by appcypher** [comment]
This has now been done (#53) by @OAyomide

**Comment by porky11** [comment]
Oh, sorry, didn't see it, thanks.
