### ISSUE TITLE
Split the list

### ISSUE THREAD

**Issue by vshymanskyy** [appcypher/awesome-wasm-langs#61]
IMHO, this list needs to be split into two:
- Languages that target wasm (i.e. emit wasm binaries, like AssemblyScript)
- Languages that run on top of wasm (i.e. are interpreted, like Lua, Prolog, ...)

**Comment by appcypher** [comment]
I agree just really busy lately. Will try rearranging the list later

**Comment by MarkuBu** [comment]
and maybe sort it in stable, unstable and wip

**Comment by appcypher** [comment]
Opted for @MarkuBu suggestion instead. I won't sort this list by compilation target vs vms. It is sort of implied from the languages themselves
