### ISSUE TITLE
Low Level Lisp

### ISSUE THREAD

**Issue by FemtoEmacs** [appcypher/awesome-wasm-langs#65]
I have noticed that you marked the Wracket language as unmaintained. The project was interesting, so it is a pity that the author discontinued his work. However, Low Level Lisp shares the same philosophy as Wracket, therefore, it is a good candidate to the list of awesome-wasm-langs. Low Level Lisp is actively maintained and well documented. It has a few advantages over Wracket: (1) The wasCm compiler generates sexpr, instead of strings; (2) It shares its linear memory with Javascript; (3) It deals correctly with local variables; (4) It can use Javascript for input/output; (5) Its programs can be executed in Lisp, as well as in WebAssembly. Here is the page:

https://github.com/FemtoEmacs/wasCm

**Comment by meugite** [comment]
Congratulations.
This is a big step for the world of functional computing

**Comment by appcypher** [comment]
@FemtoEmacs That is great to hear. Can you create a pull request for it?

**Comment by appcypher** [comment]
Added in 6e2e09c513dbf1c92c9cb25a55d4235e0fe4a436
