### ISSUE TITLE
Add Artichoke Ruby Wasm playground

### ISSUE THREAD

**Issue by lopopolo** [appcypher/awesome-wasm-langs#76]
Hi 👋 I'm working on [Artichoke Ruby](https://github.com/artichoke/artichoke). Artichoke has [native compilation to Wasm as a project goal](https://github.com/artichoke/artichoke/blob/f8e9881403a50c3ba7e2b1ffc16f205c0b5e0255/VISION.md#design-and-goals) and is usable in the browser at https://artichoke.run.

Would it be possible to have this project mentioned in the _Ruby_ section in the README?

**Comment by appcypher** [comment]
Added in 6e2e09c513dbf1c92c9cb25a55d4235e0fe4a436
